apiVersion: v1
kind: Service
metadata:
  name: scala-app
  labels:
    app: bank-account-scala
spec:
  ports:
    - port: 8080
      name: scala-app
      targetPort: 8080
  selector:
    app: bank-account-scala
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-account-scala
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 3
  selector:
    matchLabels:
      app: bank-account-scala
  template:
    metadata:
      labels:
        app: bank-account-scala
    spec:
      containers:
        - name: scala-app
          image: surge-scala-sample:0.1.0-SNAPSHOT
          imagePullPolicy: Never
          resources:
            requests:
              memory: "250Mi"
            limits:
              memory: "250Mi"
          ports:
            - containerPort: 25520
              name: akka-remoting
              protocol: TCP
            - containerPort: 8080
              name: scala-app
              protocol: TCP
          env:
            - name: "AKKA_REMOTING_HOST"
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: "BANK_ACCOUNT_HOST"
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: "BANK_ACCOUNT_PORT"
              value: "8080"
            - name: "KAFKA_BROKERS"
              value: "my-cluster-kafka-bootstrap:9092"
